app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_saveHistory:
    path : /saveHistory
    controller: AppBundle:Default:saveHistory
    
app_listCurrentHistory:
    path : /listCurrentHistory
    controller: AppBundle:Default:listCurrentHistory
    